//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOfficeTramites.wcfTramite {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BackOfficeTramites.wcfTramite.Empleado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BackOfficeTramites.wcfTramite.Solicitante))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((this.DocumentoField.Equals(value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empleado", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Empleado : BackOfficeTramites.wcfTramite.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoraInicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraFin {
            get {
                return this.HoraFinField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraFinField, value) != true)) {
                    this.HoraFinField = value;
                    this.RaisePropertyChanged("HoraFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoraInicio {
            get {
                return this.HoraInicioField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraInicioField, value) != true)) {
                    this.HoraInicioField = value;
                    this.RaisePropertyChanged("HoraInicio");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitante", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Solicitante : BackOfficeTramites.wcfTramite.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((this.TelefonoField.Equals(value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documentacion", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Documentacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoInternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LugarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomDocumentacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoInterno {
            get {
                return this.CodigoInternoField;
            }
            set {
                if ((this.CodigoInternoField.Equals(value) != true)) {
                    this.CodigoInternoField = value;
                    this.RaisePropertyChanged("CodigoInterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lugar {
            get {
                return this.LugarField;
            }
            set {
                if ((object.ReferenceEquals(this.LugarField, value) != true)) {
                    this.LugarField = value;
                    this.RaisePropertyChanged("Lugar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomDocumentacion {
            get {
                return this.NomDocumentacionField;
            }
            set {
                if ((object.ReferenceEquals(this.NomDocumentacionField, value) != true)) {
                    this.NomDocumentacionField = value;
                    this.RaisePropertyChanged("NomDocumentacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Solicitud", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Solicitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BackOfficeTramites.wcfTramite.Solicitante SolicitanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BackOfficeTramites.wcfTramite.Tramite TramiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaHora {
            get {
                return this.FechaHoraField;
            }
            set {
                if ((this.FechaHoraField.Equals(value) != true)) {
                    this.FechaHoraField = value;
                    this.RaisePropertyChanged("FechaHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BackOfficeTramites.wcfTramite.Solicitante Solicitante {
            get {
                return this.SolicitanteField;
            }
            set {
                if ((object.ReferenceEquals(this.SolicitanteField, value) != true)) {
                    this.SolicitanteField = value;
                    this.RaisePropertyChanged("Solicitante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BackOfficeTramites.wcfTramite.Tramite Tramite {
            get {
                return this.TramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.TramiteField, value) != true)) {
                    this.TramiteField = value;
                    this.RaisePropertyChanged("Tramite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tramite", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class Tramite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BackOfficeTramites.wcfTramite.Documentacion[] DocumentacionExigidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoTramite {
            get {
                return this.CodigoTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoTramiteField, value) != true)) {
                    this.CodigoTramiteField = value;
                    this.RaisePropertyChanged("CodigoTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BackOfficeTramites.wcfTramite.Documentacion[] DocumentacionExigida {
            get {
                return this.DocumentacionExigidaField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentacionExigidaField, value) != true)) {
                    this.DocumentacionExigidaField = value;
                    this.RaisePropertyChanged("DocumentacionExigida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTramite {
            get {
                return this.NombreTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTramiteField, value) != true)) {
                    this.NombreTramiteField = value;
                    this.RaisePropertyChanged("NombreTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoHorasExtra", Namespace="http://schemas.datacontract.org/2004/07/EntidadesCompartidas")]
    [System.SerializableAttribute()]
    public partial class EmpleadoHorasExtra : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BackOfficeTramites.wcfTramite.Empleado EmpleadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinutosExtraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BackOfficeTramites.wcfTramite.Empleado Empleado {
            get {
                return this.EmpleadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoField, value) != true)) {
                    this.EmpleadoField = value;
                    this.RaisePropertyChanged("Empleado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinutosExtra {
            get {
                return this.MinutosExtraField;
            }
            set {
                if ((this.MinutosExtraField.Equals(value) != true)) {
                    this.MinutosExtraField = value;
                    this.RaisePropertyChanged("MinutosExtra");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfTramite.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        BackOfficeTramites.wcfTramite.CompositeType GetDataUsingDataContract(BackOfficeTramites.wcfTramite.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.CompositeType> GetDataUsingDataContractAsync(BackOfficeTramites.wcfTramite.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogueoUsuario", ReplyAction="http://tempuri.org/IService/LogueoUsuarioResponse")]
        BackOfficeTramites.wcfTramite.Usuario LogueoUsuario(int documento, string contraseana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/LogueoUsuario", ReplyAction="http://tempuri.org/IService/LogueoUsuarioResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Usuario> LogueoUsuarioAsync(int documento, string contraseana);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarUsuario", ReplyAction="http://tempuri.org/IService/BuscarUsuarioResponse")]
        BackOfficeTramites.wcfTramite.Usuario BuscarUsuario(int documento, BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarUsuario", ReplyAction="http://tempuri.org/IService/BuscarUsuarioResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Usuario> BuscarUsuarioAsync(int documento, BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaUsuario", ReplyAction="http://tempuri.org/IService/AltaUsuarioResponse")]
        void AltaUsuario(BackOfficeTramites.wcfTramite.Usuario usuario, BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaUsuario", ReplyAction="http://tempuri.org/IService/AltaUsuarioResponse")]
        System.Threading.Tasks.Task AltaUsuarioAsync(BackOfficeTramites.wcfTramite.Usuario usuario, BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarUsuario", ReplyAction="http://tempuri.org/IService/ModificarUsuarioResponse")]
        void ModificarUsuario(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarUsuario", ReplyAction="http://tempuri.org/IService/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task ModificarUsuarioAsync(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BajaUsuario", ReplyAction="http://tempuri.org/IService/BajaUsuarioResponse")]
        void BajaUsuario(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BajaUsuario", ReplyAction="http://tempuri.org/IService/BajaUsuarioResponse")]
        System.Threading.Tasks.Task BajaUsuarioAsync(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarDocumentacion", ReplyAction="http://tempuri.org/IService/BuscarDocumentacionResponse")]
        BackOfficeTramites.wcfTramite.Documentacion BuscarDocumentacion(int codigoInterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarDocumentacion", ReplyAction="http://tempuri.org/IService/BuscarDocumentacionResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Documentacion> BuscarDocumentacionAsync(int codigoInterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarDocumentacionAux", ReplyAction="http://tempuri.org/IService/BuscarDocumentacionAuxResponse")]
        BackOfficeTramites.wcfTramite.Documentacion BuscarDocumentacionAux(int codigoInterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarDocumentacionAux", ReplyAction="http://tempuri.org/IService/BuscarDocumentacionAuxResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Documentacion> BuscarDocumentacionAuxAsync(int codigoInterno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaDocumentacion", ReplyAction="http://tempuri.org/IService/AltaDocumentacionResponse")]
        void AltaDocumentacion(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaDocumentacion", ReplyAction="http://tempuri.org/IService/AltaDocumentacionResponse")]
        System.Threading.Tasks.Task AltaDocumentacionAsync(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarDocumentacion", ReplyAction="http://tempuri.org/IService/ModificarDocumentacionResponse")]
        void ModificarDocumentacion(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarDocumentacion", ReplyAction="http://tempuri.org/IService/ModificarDocumentacionResponse")]
        System.Threading.Tasks.Task ModificarDocumentacionAsync(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BajaDocumentacion", ReplyAction="http://tempuri.org/IService/BajaDocumentacionResponse")]
        void BajaDocumentacion(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BajaDocumentacion", ReplyAction="http://tempuri.org/IService/BajaDocumentacionResponse")]
        System.Threading.Tasks.Task BajaDocumentacionAsync(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/listadoDocumentacion", ReplyAction="http://tempuri.org/IService/listadoDocumentacionResponse")]
        BackOfficeTramites.wcfTramite.Documentacion[] listadoDocumentacion(BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/listadoDocumentacion", ReplyAction="http://tempuri.org/IService/listadoDocumentacionResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Documentacion[]> listadoDocumentacionAsync(BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaSolicitud", ReplyAction="http://tempuri.org/IService/AltaSolicitudResponse")]
        void AltaSolicitud(BackOfficeTramites.wcfTramite.Solicitud solicitud, BackOfficeTramites.wcfTramite.Usuario empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaSolicitud", ReplyAction="http://tempuri.org/IService/AltaSolicitudResponse")]
        System.Threading.Tasks.Task AltaSolicitudAsync(BackOfficeTramites.wcfTramite.Solicitud solicitud, BackOfficeTramites.wcfTramite.Usuario empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/listadoSolicitud", ReplyAction="http://tempuri.org/IService/listadoSolicitudResponse")]
        BackOfficeTramites.wcfTramite.Solicitud[] listadoSolicitud(BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/listadoSolicitud", ReplyAction="http://tempuri.org/IService/listadoSolicitudResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Solicitud[]> listadoSolicitudAsync(BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarSolicitud", ReplyAction="http://tempuri.org/IService/BuscarSolicitudResponse")]
        BackOfficeTramites.wcfTramite.Solicitud BuscarSolicitud(int documento, BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarSolicitud", ReplyAction="http://tempuri.org/IService/BuscarSolicitudResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Solicitud> BuscarSolicitudAsync(int documento, BackOfficeTramites.wcfTramite.Usuario usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CambiarEstadoSolicitud", ReplyAction="http://tempuri.org/IService/CambiarEstadoSolicitudResponse")]
        void CambiarEstadoSolicitud(int solicitud, int accion, BackOfficeTramites.wcfTramite.Empleado usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CambiarEstadoSolicitud", ReplyAction="http://tempuri.org/IService/CambiarEstadoSolicitudResponse")]
        System.Threading.Tasks.Task CambiarEstadoSolicitudAsync(int solicitud, int accion, BackOfficeTramites.wcfTramite.Empleado usLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarTramite", ReplyAction="http://tempuri.org/IService/BuscarTramiteResponse")]
        BackOfficeTramites.wcfTramite.Tramite BuscarTramite(string codigoTramite, BackOfficeTramites.wcfTramite.Usuario empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BuscarTramite", ReplyAction="http://tempuri.org/IService/BuscarTramiteResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Tramite> BuscarTramiteAsync(string codigoTramite, BackOfficeTramites.wcfTramite.Usuario empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaTramite", ReplyAction="http://tempuri.org/IService/AltaTramiteResponse")]
        void AltaTramite(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaTramite", ReplyAction="http://tempuri.org/IService/AltaTramiteResponse")]
        System.Threading.Tasks.Task AltaTramiteAsync(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarTramite", ReplyAction="http://tempuri.org/IService/ModificarTramiteResponse")]
        void ModificarTramite(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ModificarTramite", ReplyAction="http://tempuri.org/IService/ModificarTramiteResponse")]
        System.Threading.Tasks.Task ModificarTramiteAsync(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BajaTramite", ReplyAction="http://tempuri.org/IService/BajaTramiteResponse")]
        void BajaTramite(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/BajaTramite", ReplyAction="http://tempuri.org/IService/BajaTramiteResponse")]
        System.Threading.Tasks.Task BajaTramiteAsync(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTramites", ReplyAction="http://tempuri.org/IService/ListarTramitesResponse")]
        BackOfficeTramites.wcfTramite.Tramite[] ListarTramites();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ListarTramites", ReplyAction="http://tempuri.org/IService/ListarTramitesResponse")]
        System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Tramite[]> ListarTramitesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/listadoTramitesXml", ReplyAction="http://tempuri.org/IService/listadoTramitesXmlResponse")]
        string listadoTramitesXml();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/listadoTramitesXml", ReplyAction="http://tempuri.org/IService/listadoTramitesXmlResponse")]
        System.Threading.Tasks.Task<string> listadoTramitesXmlAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaHoraExtra", ReplyAction="http://tempuri.org/IService/AltaHoraExtraResponse")]
        void AltaHoraExtra(BackOfficeTramites.wcfTramite.EmpleadoHorasExtra hemp, BackOfficeTramites.wcfTramite.Empleado empLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AltaHoraExtra", ReplyAction="http://tempuri.org/IService/AltaHoraExtraResponse")]
        System.Threading.Tasks.Task AltaHoraExtraAsync(BackOfficeTramites.wcfTramite.EmpleadoHorasExtra hemp, BackOfficeTramites.wcfTramite.Empleado empLog);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : BackOfficeTramites.wcfTramite.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<BackOfficeTramites.wcfTramite.IService>, BackOfficeTramites.wcfTramite.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BackOfficeTramites.wcfTramite.CompositeType GetDataUsingDataContract(BackOfficeTramites.wcfTramite.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.CompositeType> GetDataUsingDataContractAsync(BackOfficeTramites.wcfTramite.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public BackOfficeTramites.wcfTramite.Usuario LogueoUsuario(int documento, string contraseana) {
            return base.Channel.LogueoUsuario(documento, contraseana);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Usuario> LogueoUsuarioAsync(int documento, string contraseana) {
            return base.Channel.LogueoUsuarioAsync(documento, contraseana);
        }
        
        public BackOfficeTramites.wcfTramite.Usuario BuscarUsuario(int documento, BackOfficeTramites.wcfTramite.Usuario usLog) {
            return base.Channel.BuscarUsuario(documento, usLog);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Usuario> BuscarUsuarioAsync(int documento, BackOfficeTramites.wcfTramite.Usuario usLog) {
            return base.Channel.BuscarUsuarioAsync(documento, usLog);
        }
        
        public void AltaUsuario(BackOfficeTramites.wcfTramite.Usuario usuario, BackOfficeTramites.wcfTramite.Usuario usLog) {
            base.Channel.AltaUsuario(usuario, usLog);
        }
        
        public System.Threading.Tasks.Task AltaUsuarioAsync(BackOfficeTramites.wcfTramite.Usuario usuario, BackOfficeTramites.wcfTramite.Usuario usLog) {
            return base.Channel.AltaUsuarioAsync(usuario, usLog);
        }
        
        public void ModificarUsuario(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.ModificarUsuario(empleado, empLog);
        }
        
        public System.Threading.Tasks.Task ModificarUsuarioAsync(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.ModificarUsuarioAsync(empleado, empLog);
        }
        
        public void BajaUsuario(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.BajaUsuario(empleado, empLog);
        }
        
        public System.Threading.Tasks.Task BajaUsuarioAsync(BackOfficeTramites.wcfTramite.Usuario empleado, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.BajaUsuarioAsync(empleado, empLog);
        }
        
        public BackOfficeTramites.wcfTramite.Documentacion BuscarDocumentacion(int codigoInterno) {
            return base.Channel.BuscarDocumentacion(codigoInterno);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Documentacion> BuscarDocumentacionAsync(int codigoInterno) {
            return base.Channel.BuscarDocumentacionAsync(codigoInterno);
        }
        
        public BackOfficeTramites.wcfTramite.Documentacion BuscarDocumentacionAux(int codigoInterno) {
            return base.Channel.BuscarDocumentacionAux(codigoInterno);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Documentacion> BuscarDocumentacionAuxAsync(int codigoInterno) {
            return base.Channel.BuscarDocumentacionAuxAsync(codigoInterno);
        }
        
        public void AltaDocumentacion(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.AltaDocumentacion(documentacion, empLog);
        }
        
        public System.Threading.Tasks.Task AltaDocumentacionAsync(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.AltaDocumentacionAsync(documentacion, empLog);
        }
        
        public void ModificarDocumentacion(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.ModificarDocumentacion(documentacion, empLog);
        }
        
        public System.Threading.Tasks.Task ModificarDocumentacionAsync(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.ModificarDocumentacionAsync(documentacion, empLog);
        }
        
        public void BajaDocumentacion(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.BajaDocumentacion(documentacion, empLog);
        }
        
        public System.Threading.Tasks.Task BajaDocumentacionAsync(BackOfficeTramites.wcfTramite.Documentacion documentacion, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.BajaDocumentacionAsync(documentacion, empLog);
        }
        
        public BackOfficeTramites.wcfTramite.Documentacion[] listadoDocumentacion(BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.listadoDocumentacion(empLog);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Documentacion[]> listadoDocumentacionAsync(BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.listadoDocumentacionAsync(empLog);
        }
        
        public void AltaSolicitud(BackOfficeTramites.wcfTramite.Solicitud solicitud, BackOfficeTramites.wcfTramite.Usuario empLog) {
            base.Channel.AltaSolicitud(solicitud, empLog);
        }
        
        public System.Threading.Tasks.Task AltaSolicitudAsync(BackOfficeTramites.wcfTramite.Solicitud solicitud, BackOfficeTramites.wcfTramite.Usuario empLog) {
            return base.Channel.AltaSolicitudAsync(solicitud, empLog);
        }
        
        public BackOfficeTramites.wcfTramite.Solicitud[] listadoSolicitud(BackOfficeTramites.wcfTramite.Usuario usLog) {
            return base.Channel.listadoSolicitud(usLog);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Solicitud[]> listadoSolicitudAsync(BackOfficeTramites.wcfTramite.Usuario usLog) {
            return base.Channel.listadoSolicitudAsync(usLog);
        }
        
        public BackOfficeTramites.wcfTramite.Solicitud BuscarSolicitud(int documento, BackOfficeTramites.wcfTramite.Usuario usLog) {
            return base.Channel.BuscarSolicitud(documento, usLog);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Solicitud> BuscarSolicitudAsync(int documento, BackOfficeTramites.wcfTramite.Usuario usLog) {
            return base.Channel.BuscarSolicitudAsync(documento, usLog);
        }
        
        public void CambiarEstadoSolicitud(int solicitud, int accion, BackOfficeTramites.wcfTramite.Empleado usLog) {
            base.Channel.CambiarEstadoSolicitud(solicitud, accion, usLog);
        }
        
        public System.Threading.Tasks.Task CambiarEstadoSolicitudAsync(int solicitud, int accion, BackOfficeTramites.wcfTramite.Empleado usLog) {
            return base.Channel.CambiarEstadoSolicitudAsync(solicitud, accion, usLog);
        }
        
        public BackOfficeTramites.wcfTramite.Tramite BuscarTramite(string codigoTramite, BackOfficeTramites.wcfTramite.Usuario empLog) {
            return base.Channel.BuscarTramite(codigoTramite, empLog);
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Tramite> BuscarTramiteAsync(string codigoTramite, BackOfficeTramites.wcfTramite.Usuario empLog) {
            return base.Channel.BuscarTramiteAsync(codigoTramite, empLog);
        }
        
        public void AltaTramite(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.AltaTramite(tramite, empLog);
        }
        
        public System.Threading.Tasks.Task AltaTramiteAsync(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.AltaTramiteAsync(tramite, empLog);
        }
        
        public void ModificarTramite(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.ModificarTramite(tramite, empLog);
        }
        
        public System.Threading.Tasks.Task ModificarTramiteAsync(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.ModificarTramiteAsync(tramite, empLog);
        }
        
        public void BajaTramite(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.BajaTramite(tramite, empLog);
        }
        
        public System.Threading.Tasks.Task BajaTramiteAsync(BackOfficeTramites.wcfTramite.Tramite tramite, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.BajaTramiteAsync(tramite, empLog);
        }
        
        public BackOfficeTramites.wcfTramite.Tramite[] ListarTramites() {
            return base.Channel.ListarTramites();
        }
        
        public System.Threading.Tasks.Task<BackOfficeTramites.wcfTramite.Tramite[]> ListarTramitesAsync() {
            return base.Channel.ListarTramitesAsync();
        }
        
        public string listadoTramitesXml() {
            return base.Channel.listadoTramitesXml();
        }
        
        public System.Threading.Tasks.Task<string> listadoTramitesXmlAsync() {
            return base.Channel.listadoTramitesXmlAsync();
        }
        
        public void AltaHoraExtra(BackOfficeTramites.wcfTramite.EmpleadoHorasExtra hemp, BackOfficeTramites.wcfTramite.Empleado empLog) {
            base.Channel.AltaHoraExtra(hemp, empLog);
        }
        
        public System.Threading.Tasks.Task AltaHoraExtraAsync(BackOfficeTramites.wcfTramite.EmpleadoHorasExtra hemp, BackOfficeTramites.wcfTramite.Empleado empLog) {
            return base.Channel.AltaHoraExtraAsync(hemp, empLog);
        }
    }
}
